name: Build DevForge

on:
  push:
    branches: [ main, release/*, github-workflow ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        shell: pwsh
        run: |
          # Set GitHub Packages registry for scoped packages
          npm config set @microsoft:registry https://npm.pkg.github.com/
          npm config set @vscode:registry https://npm.pkg.github.com/
          # Set auth token for GitHub Packages
          npm config set '//npm.pkg.github.com/:_authToken' '${{ github.token }}'
          # Set network timeouts
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          # Install dependencies
          npm install
          npm install -g node-gyp
          npm install -g gulp-cli
      - name: Build
        continue-on-error: true
        run: |
          npm run buildreact
          # Clean build directories first
          gulp clean-out-build || true
          # Disable mangling to avoid node_modules issues
          gulp compile-build-without-mangling || (echo "Compilation failed but continuing..." && exit 0)
          # Continue with minification even if compilation had warnings
          gulp vscode-win32-x64-min || (echo "Minification failed but continuing..." && exit 0)
      - name: Package
        run: |
          mkdir -p .build/win32-x64
          Compress-Archive -Path ..\VSCode-win32-x64\* -DestinationPath .build\win32-x64\devforge-win32-x64.zip
        shell: pwsh

      - name: Generate checksum
        run: |
          cd .build/win32-x64
          $hash = Get-FileHash -Algorithm SHA256 devforge-win32-x64.zip
          $hash.Hash | Out-File -Encoding ascii devforge-win32-x64.zip.sha256
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devforge-win32-x64
          path: |
            .build/win32-x64/devforge-win32-x64.zip
            .build/win32-x64/devforge-win32-x64.zip.sha256
  build-windows-arm64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        shell: pwsh
        run: |
          # Set GitHub Packages registry for scoped packages
          npm config set @microsoft:registry https://npm.pkg.github.com/
          npm config set @vscode:registry https://npm.pkg.github.com/
          # Set auth token for GitHub Packages
          npm config set '//npm.pkg.github.com/:_authToken' '${{ github.token }}'
          # Set network timeouts
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          # Install dependencies
          npm install
          npm install -g node-gyp
          npm install -g gulp-cli
      - name: Build
        continue-on-error: true
        run: |
          npm run buildreact
          # Clean build directories first
          gulp clean-out-build || true
          # Disable mangling to avoid node_modules issues
          gulp compile-build-without-mangling || (echo "Compilation failed but continuing..." && exit 0)
          # Continue with minification even if compilation had warnings
          gulp vscode-win32-arm64-min || (echo "Minification failed but continuing..." && exit 0)
      - name: Package
        run: |
          mkdir -p .build/win32-arm64
          Compress-Archive -Path ..\VSCode-win32-arm64\* -DestinationPath .build\win32-arm64\devforge-win32-arm64.zip
        shell: pwsh

      - name: Generate checksum
        run: |
          cd .build/win32-arm64
          $hash = Get-FileHash -Algorithm SHA256 devforge-win32-arm64.zip
          $hash.Hash | Out-File -Encoding ascii devforge-win32-arm64.zip.sha256
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devforge-win32-arm64
          path: |
            .build/win32-arm64/devforge-win32-arm64.zip
            .build/win32-arm64/devforge-win32-arm64.zip.sha256
